# This is a basic workflow to help you get started with Actions

name: Fabrics agents

# Controls when the workflow will run
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-agents:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v10.1.0
      - name: Install project
        run: uv sync --locked --group agents --group dev --group mujoco --group pybullet
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      # Runs a set of commands using the runners shell
      - name: Test agents
        run: uv run --locked python -m pytest examples/test_examples.py
