# This is a basic workflow to help you get started with Actions

name: Testing Differential Geometry

# Controls when the workflow will run
on: 
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v10.1.0
      - name: Install project
        run: uv sync --locked --group dev
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      # Runs a set of commands using the runners shell
      - name: Run pytest
        run: uv run --locked python -m pytest --cov fabrics --cov-fail-under=80 tests/
